CREATE SCHEMA UNIVERSITY

CREATE TABLE UNIVERSITY.DEPARTMENTS (
    ID int NOT NULL,
    NAME varchar(100) NOT NULL,
    ACRONYM varchar(10) NOT NULL,
    PRIMARY KEY(ID)
);

INSERT INTO UNIVERSITY.DEPARTMENTS (ID, ACRONYM, NAME) VALUES (0, 'ФКТИ', 'Факультет компьютерных технологий и информатики');
INSERT INTO UNIVERSITY.DEPARTMENTS (ID, ACRONYM, NAME) VALUES (1, 'ФЭЛ', 'Факультет электроники');
INSERT INTO UNIVERSITY.DEPARTMENTS (ID, ACRONYM, NAME) VALUES (2, 'ФЭА', 'Факультет электротехники и автоматики');

CREATE TABLE UNIVERSITY.GROUPS (
    ID int NOT NULL,
    DEPARTMENT_ID int NOT NULL,
    TRAINING_PROGRAM varchar(100) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID)
);


INSERT INTO UNIVERSITY.GROUPS (ID, DEPARTMENT_ID, TRAINING_PROGRAM) VALUES (1303, 0, 'Программная инженерия');
INSERT INTO UNIVERSITY.GROUPS (ID, DEPARTMENT_ID, TRAINING_PROGRAM) VALUES (1304, 0, 'Программная инженерия');
INSERT INTO UNIVERSITY.GROUPS (ID, DEPARTMENT_ID, TRAINING_PROGRAM) VALUES (1381, 0, 'Прикладная математика и информатика');
INSERT INTO UNIVERSITY.GROUPS (ID, DEPARTMENT_ID, TRAINING_PROGRAM) VALUES (1382, 0, 'Прикладная математика и информатика');
INSERT INTO UNIVERSITY.GROUPS (ID, DEPARTMENT_ID, TRAINING_PROGRAM ) VALUES (1255, 1, 'Микроконтроллеры и микропроцессоры');
INSERT INTO UNIVERSITY.GROUPS (ID, DEPARTMENT_ID, TRAINING_PROGRAM ) VALUES (1256, 1, 'Вакуумная и плазменная электроника');


CREATE TABLE UNIVERSITY.STUDENTS (
ID int NOT NULL,
LAST_NAME varchar(255) NOT NULl,
FIRST_NAME varchar(255) NOT NULL,
GROUP_ID int NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (GROUP_ID) REFERENCES UNIVERSITY.GROUPS(ID)
);